package com.neopixl.lesmovies

/**
 * Created by Yvan Moté on 2019-10-17.
 */
class ModelGenerator {
    val allMovies: Array<Movie> by lazy {
        arrayOf(Movie("Harry Potter à l'école des sorciers", "Un jour de juillet, peu avant son onzième anniversaire, Harry reçoit une lettre de Poudlard, l'école de magie et de sorcellerie, l'invitant à s'y présenter pour la rentrée des classes, mais son oncle la lui confisque avant qu'il ne puisse la lire, ne voulant pas que Harry devienne sorcier. L'école ne recevant aucune réponse, d'autres lettres, en nombre croissant, sont envoyées en vain par la directrice-adjointe de Poudlard, Minerva McGonagall. Finalement, le directeur Albus Dumbledore envoie Rubeus Hagrid, un demi-géant, gardien des clés et des lieux à Poudlard, chercher Harry le jour de son anniversaire, le 31 juillet.", 2001),
            Movie("Retour vers le futur", "L'intrigue relate le voyage dans le passé d'un adolescent, Marty McFly, à bord d'une machine à voyager dans le temps fabriquée par le docteur Emmett Brown à partir d'une voiture de modèle DeLorean DMC-12. Parti de l'année 1985 et propulsé en 1955, Marty, aidé du « Doc » de 1955, doit résoudre les paradoxes temporels provoqués par ses interventions dans le passé et trouver le moyen de faire fonctionner la machine pour retourner à son époque d'origine.", 1985),
            Movie("Alien", "En 2122, le cargo spatial Nostromo, de retour vers la Terre avec son chargement de minerai, capte un signal sonore émis depuis un planétoïde isolé. L'ordinateur de bord du vaisseau — appelé « Maman » — interrompt alors le trajet du Nostromo et réveille l'équipage maintenu en biostase (sommeil artificiel).", 1979),
            Movie("Terminator", "Arrivés en 1984 nus comme des vers après leur voyage temporel, les deux antagonistes du futur, après avoir récupéré chacun de son côté des vêtements et de l'armement, se lancent à la recherche de Sarah Connor. À l'époque, la jeune femme travaille comme serveuse dans un restaurant de Los Angeles. Elle est cependant alertée lorsqu'une homonyme, une autre Sarah Connor, est assassinée (par le Terminator) à son domicile, l'information étant relayée à la télévision, ce qui ne manque pas d’inquiéter Sarah.", 1984),
            Movie("Jurassic Park", "John Parker Hammond, le PDG de la puissante compagnie InGen, parvient à donner vie à des dinosaures grâce à la génétique et décide de les utiliser dans le cadre d’un parc d'attractions qu’il compte ouvrir sur une île au large du Costa Rica. Avant l'ouverture, il fait visiter le parc à un groupe d'experts pour obtenir leur aval. Pendant la visite, une tempête éclate et un informaticien corrompu par une entreprise rivale en profite pour couper les systèmes de sécurité afin de voler des embryons de dinosaures. En l'absence de tout système de sécurité pendant plusieurs heures, les dinosaures s'échappent sans mal, mais le cauchemar des visiteurs ne fait que commencer...", 1993),
            Movie("Les Évadés", "947. Andy Dufresne, un banquier américain, est jugé coupable du meurtre de sa femme et de l'amant avec qui elle le trompait. Pour ce double meurtre, et malgré qu'il ait clamé son innocence depuis le début, il est condamné à deux peines de prison à vie consécutives. Il est ensuite emprisonné au pénitencier fédéral de Shawshank dans l'État du Maine où il est « accueilli » avec les autres nouveaux détenus par Samuel Norton, le directeur de la prison. Norton, un homme ambitieux et pétri de valeurs religieuses traditionnelles, est épaulé par un gardien-chef brutal et sans pitié, le capitaine Byron Hadley qui ne craint pas de recourir à une violence aveugle (jusqu'à la mort de détenu, si nécessaire) afin de faire respecter la discipline.", 1994),
            Movie("Demolition man", "À Los Angeles en 1996, Simon Phoenix, un psychopathe traqué par la police, s'est emparé d'une trentaine d'otages avant de se réfugier dans une planque pleine d'armes et d'explosifs. Alors que ses supérieurs hésitent quant aux méthodes à employer, le sergent de police John Spartan, surnommé Demolition Man (littéralement « le démolisseur ») en raison de ses méthodes expéditives, décide de passer à l'action et parvient à s'introduire dans le repaire de Phoenix. Ce dernier refuse de se rendre et déclenche une formidable explosion durant laquelle les 30 otages trouvent la mort. John Spartan est accusé d'homicide par imprudence et est condamné à une longue peine d'hibernation et de rééducation au Cryo-Pénitencier de Californie : il y est cryogénisé et devra subir pendant 70 ans une sorte de lavage de cerveau, au terme duquel il devrait être un citoyen qui ne représente plus aucun danger pour les autres, avant d'être sorti de son état d'hibernation. Phoenix est également condamné à une peine de détention à vie au Cryo-Pénitencier…", 1993),
            Movie("Seven", "Fraîchement transféré à la brigade criminelle de New York, le policier David Mills doit faire équipe un temps avec celui qu'il va remplacer : William Somerset, un officier de police judiciaire affecté aux homicides, bientôt à la retraite. Les deux hommes sont alors chargés d'une enquête sur un tueur psychopathe qui planifie méthodiquement ses meurtres, en fonction des sept péchés capitaux : la gourmandise, l'avarice, la paresse, la luxure, l'orgueil, l'envie et la colère." , 1995),
            Movie("Shaun of the Dead", "Shaun (Simon Pegg), vendeur dans un magasin d'électroménager de la banlieue de Londres, mène une vie routinière tournant autour de la pratique des jeux vidéo et la fréquentation de son pub favori, Le Winchester, avec Ed (Nick Frost), son meilleur ami. Sa petite amie Liz (Kate Ashfield) n'est pas satisfaite de leur relation et finit par décider de le quitter. Par ailleurs, Shaun a des problèmes relationnels avec son beau-père Philip (Bill Nighy) avec lequel il ne s'est jamais entendu et qu'il ne considère pas comme son père. Lorsque Liz le quitte, Shaun noie sa peine au Winchester avec Ed. Après une nuit de beuverie, ils se réveillent dans un monde peuplé de morts-vivants. Ils ne s'en rendent compte que lorsque Shaun se fait attaquer par deux zombies, qu'ils prenaient pour des ivrognes. ",2004))
    }
}
